name: Create doc issues on PR merge

# Action that creates issues in cockroachdb/docs when a PR is merged from
# cockroachdb/cockroach in the master or release-* branch and has a
# release note in the PR body.

on:
  pull_request:
    branches:
      - master
      - 'release-*'

    types: [closed]

jobs:
  create-doc-issue:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true }}
    env:
      PR_BODY: ${{ github.event.pull_request.body }}
      PR_TITLE: ${{ github.event.pull_request.title }}
      PR_NUMBER: ${{ github.event.pull_request.number }}
      REGEX: '[rR]elease [nN]otes? ?(\((\w.+)\):|:) (\w+.*)$'
    steps:
      - uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ env.PR_BODY }}
          regex: ${{ env.REGEX }}
          flags: 'gm'

      - name: Format any release note from PR body
        id: body
        run: |
          echo '${{ env.PR_BODY }}' > body.txt
          cat body.txt | sed -n '/[rR]elease [nN]ote/,$p' > temp
          sed -r 's/[rR]elease [nN]otes? ?\(.*: ?/''/g' temp > note
          body=$(cat note)
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}"
          echo ::set-output name=body::$body

      - name: Create docs issue
        if: |
          steps.regex-match.outputs.match != '' &&
          startsWith(steps.regex-match.outputs.group3, 'None') == false &&
          startsWith(steps.regex-match.outputs.group3, 'none') == false &&
          startsWith(steps.regex-match.outputs.group2, 'Bug') == false &&
          startsWith(steps.regex-match.outputs.group2, 'bug') == false &&
          startsWith(steps.regex-match.outputs.group2, 'Performance') == false &&
          startsWith(steps.regex-match.outputs.group2, 'performance') == false
        uses: maxkomarychev/oction-create-issue@v0.7.1
        id: create-issue
        with:
          token: ${{ secrets.PAT }}
          owner: yzdocs 
          repo: docs 
          title: ${{ env.PR_TITLE }}
          body: |
            PR: https://github.com/cockroachdb/cockroach/pull/${{ env.PR_NUMBER }}

            From release notes:
            > ${{ steps.body.outputs.body }}
